name: Pull latest data from Mojang API

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '25 */6 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        node update_blocklist.js
    - name: Generate todo.txt
      run: |-
        comm -23 <(sort -u data/current.txt) <(awk -F= '{print $1}' data/identified.txt |sort -u) | sort -u > data/todo.txt
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Blocklist updated: ${timestamp}" || exit 0
        git push
